//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioTeste.nfse {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="nfse.WSnfseSoap")]
    public interface WSnfseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autorizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Autorizar(EnvioTeste.nfse.CapaAutorizacaoNfse obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autorizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutorizarAsync(EnvioTeste.nfse.CapaAutorizacaoNfse obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Consultar(EnvioTeste.nfse.Consultar referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultarAsync(EnvioTeste.nfse.Consultar referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_testes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Consultar_testes(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_testes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Consultar_testesAsync(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cancelar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Cancelar(EnvioTeste.nfse.Cancelar referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cancelar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CancelarAsync(EnvioTeste.nfse.Cancelar referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cancelar_testes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Cancelar_testes(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cancelar_testes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Cancelar_testesAsync(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarNfse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GerarNfse(int id_grv, bool _isdev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GerarNfseAsync(int id_grv, bool _isdev);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CapaAutorizacaoNfse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Autorizar autorizarField;
        
        private bool homologacaoField;
        
        private int identificador_notaField;
        
        private int id_usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Autorizar autorizar {
            get {
                return this.autorizarField;
            }
            set {
                this.autorizarField = value;
                this.RaisePropertyChanged("autorizar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool homologacao {
            get {
                return this.homologacaoField;
            }
            set {
                this.homologacaoField = value;
                this.RaisePropertyChanged("homologacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int identificador_nota {
            get {
                return this.identificador_notaField;
            }
            set {
                this.identificador_notaField = value;
                this.RaisePropertyChanged("identificador_nota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autorizar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string data_emissaoField;
        
        private string natureza_operacaoField;
        
        private string regime_especial_tributacaoField;
        
        private string optante_simples_nacionalField;
        
        private string incentivador_culturalField;
        
        private string tributacao_rpsField;
        
        private string codigo_obraField;
        
        private string artField;
        
        private Prestador prestadorField;
        
        private Tomador tomadorField;
        
        private Servico servicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string data_emissao {
            get {
                return this.data_emissaoField;
            }
            set {
                this.data_emissaoField = value;
                this.RaisePropertyChanged("data_emissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string natureza_operacao {
            get {
                return this.natureza_operacaoField;
            }
            set {
                this.natureza_operacaoField = value;
                this.RaisePropertyChanged("natureza_operacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string regime_especial_tributacao {
            get {
                return this.regime_especial_tributacaoField;
            }
            set {
                this.regime_especial_tributacaoField = value;
                this.RaisePropertyChanged("regime_especial_tributacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string optante_simples_nacional {
            get {
                return this.optante_simples_nacionalField;
            }
            set {
                this.optante_simples_nacionalField = value;
                this.RaisePropertyChanged("optante_simples_nacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string incentivador_cultural {
            get {
                return this.incentivador_culturalField;
            }
            set {
                this.incentivador_culturalField = value;
                this.RaisePropertyChanged("incentivador_cultural");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tributacao_rps {
            get {
                return this.tributacao_rpsField;
            }
            set {
                this.tributacao_rpsField = value;
                this.RaisePropertyChanged("tributacao_rps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string codigo_obra {
            get {
                return this.codigo_obraField;
            }
            set {
                this.codigo_obraField = value;
                this.RaisePropertyChanged("codigo_obra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("art");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Prestador prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
                this.RaisePropertyChanged("prestador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Tomador tomador {
            get {
                return this.tomadorField;
            }
            set {
                this.tomadorField = value;
                this.RaisePropertyChanged("tomador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Servico servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
                this.RaisePropertyChanged("servico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Prestador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cnpjField;
        
        private string inscricao_municipalField;
        
        private string codigo_municipioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string inscricao_municipal {
            get {
                return this.inscricao_municipalField;
            }
            set {
                this.inscricao_municipalField = value;
                this.RaisePropertyChanged("inscricao_municipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigo_municipio {
            get {
                return this.codigo_municipioField;
            }
            set {
                this.codigo_municipioField = value;
                this.RaisePropertyChanged("codigo_municipio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cancelar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenciaField;
        
        private string justificativaField;
        
        private bool homologacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string justificativa {
            get {
                return this.justificativaField;
            }
            set {
                this.justificativaField = value;
                this.RaisePropertyChanged("justificativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool homologacao {
            get {
                return this.homologacaoField;
            }
            set {
                this.homologacaoField = value;
                this.RaisePropertyChanged("homologacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenciaField;
        
        private string cnpj_prestadorField;
        
        private bool homologacaoField;
        
        private int id_usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cnpj_prestador {
            get {
                return this.cnpj_prestadorField;
            }
            set {
                this.cnpj_prestadorField = value;
                this.RaisePropertyChanged("cnpj_prestador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool homologacao {
            get {
                return this.homologacaoField;
            }
            set {
                this.homologacaoField = value;
                this.RaisePropertyChanged("homologacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliquotaField;
        
        private string discriminacaoField;
        
        private string iss_retidoField;
        
        private string item_lista_servicoField;
        
        private string codigo_tributario_municipioField;
        
        private string valor_servicosField;
        
        private string valor_deducoesField;
        
        private string valor_pisField;
        
        private string valor_cofinsField;
        
        private string valor_inssField;
        
        private string valor_irField;
        
        private string valor_csllField;
        
        private string valor_issField;
        
        private string valor_iss_retidoField;
        
        private string outras_retencoesField;
        
        private string base_calculoField;
        
        private string desconto_incondicionadoField;
        
        private string desconto_condicionadoField;
        
        private string codigo_cnaeField;
        
        private string codigo_municipioField;
        
        private string percentual_total_tributosField;
        
        private string fonte_total_tributosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string aliquota {
            get {
                return this.aliquotaField;
            }
            set {
                this.aliquotaField = value;
                this.RaisePropertyChanged("aliquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string discriminacao {
            get {
                return this.discriminacaoField;
            }
            set {
                this.discriminacaoField = value;
                this.RaisePropertyChanged("discriminacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string iss_retido {
            get {
                return this.iss_retidoField;
            }
            set {
                this.iss_retidoField = value;
                this.RaisePropertyChanged("iss_retido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string item_lista_servico {
            get {
                return this.item_lista_servicoField;
            }
            set {
                this.item_lista_servicoField = value;
                this.RaisePropertyChanged("item_lista_servico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codigo_tributario_municipio {
            get {
                return this.codigo_tributario_municipioField;
            }
            set {
                this.codigo_tributario_municipioField = value;
                this.RaisePropertyChanged("codigo_tributario_municipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string valor_servicos {
            get {
                return this.valor_servicosField;
            }
            set {
                this.valor_servicosField = value;
                this.RaisePropertyChanged("valor_servicos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string valor_deducoes {
            get {
                return this.valor_deducoesField;
            }
            set {
                this.valor_deducoesField = value;
                this.RaisePropertyChanged("valor_deducoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string valor_pis {
            get {
                return this.valor_pisField;
            }
            set {
                this.valor_pisField = value;
                this.RaisePropertyChanged("valor_pis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string valor_cofins {
            get {
                return this.valor_cofinsField;
            }
            set {
                this.valor_cofinsField = value;
                this.RaisePropertyChanged("valor_cofins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string valor_inss {
            get {
                return this.valor_inssField;
            }
            set {
                this.valor_inssField = value;
                this.RaisePropertyChanged("valor_inss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string valor_ir {
            get {
                return this.valor_irField;
            }
            set {
                this.valor_irField = value;
                this.RaisePropertyChanged("valor_ir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string valor_csll {
            get {
                return this.valor_csllField;
            }
            set {
                this.valor_csllField = value;
                this.RaisePropertyChanged("valor_csll");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string valor_iss {
            get {
                return this.valor_issField;
            }
            set {
                this.valor_issField = value;
                this.RaisePropertyChanged("valor_iss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string valor_iss_retido {
            get {
                return this.valor_iss_retidoField;
            }
            set {
                this.valor_iss_retidoField = value;
                this.RaisePropertyChanged("valor_iss_retido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string outras_retencoes {
            get {
                return this.outras_retencoesField;
            }
            set {
                this.outras_retencoesField = value;
                this.RaisePropertyChanged("outras_retencoes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string base_calculo {
            get {
                return this.base_calculoField;
            }
            set {
                this.base_calculoField = value;
                this.RaisePropertyChanged("base_calculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string desconto_incondicionado {
            get {
                return this.desconto_incondicionadoField;
            }
            set {
                this.desconto_incondicionadoField = value;
                this.RaisePropertyChanged("desconto_incondicionado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string desconto_condicionado {
            get {
                return this.desconto_condicionadoField;
            }
            set {
                this.desconto_condicionadoField = value;
                this.RaisePropertyChanged("desconto_condicionado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string codigo_cnae {
            get {
                return this.codigo_cnaeField;
            }
            set {
                this.codigo_cnaeField = value;
                this.RaisePropertyChanged("codigo_cnae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string codigo_municipio {
            get {
                return this.codigo_municipioField;
            }
            set {
                this.codigo_municipioField = value;
                this.RaisePropertyChanged("codigo_municipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string percentual_total_tributos {
            get {
                return this.percentual_total_tributosField;
            }
            set {
                this.percentual_total_tributosField = value;
                this.RaisePropertyChanged("percentual_total_tributos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string fonte_total_tributos {
            get {
                return this.fonte_total_tributosField;
            }
            set {
                this.fonte_total_tributosField = value;
                this.RaisePropertyChanged("fonte_total_tributos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string logradouroField;
        
        private string tipo_logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string codigo_municipioField;
        
        private string ufField;
        
        private string cepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipo_logradouro {
            get {
                return this.tipo_logradouroField;
            }
            set {
                this.tipo_logradouroField = value;
                this.RaisePropertyChanged("tipo_logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string codigo_municipio {
            get {
                return this.codigo_municipioField;
            }
            set {
                this.codigo_municipioField = value;
                this.RaisePropertyChanged("codigo_municipio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("cep");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tomador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cnpjField;
        
        private string cpfField;
        
        private string razao_socialField;
        
        private string emailField;
        
        private string inscricao_municipalField;
        
        private string telefoneField;
        
        private Endereco enderecoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
                this.RaisePropertyChanged("cpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string razao_social {
            get {
                return this.razao_socialField;
            }
            set {
                this.razao_socialField = value;
                this.RaisePropertyChanged("razao_social");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string inscricao_municipal {
            get {
                return this.inscricao_municipalField;
            }
            set {
                this.inscricao_municipalField = value;
                this.RaisePropertyChanged("inscricao_municipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
                this.RaisePropertyChanged("telefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("endereco");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSnfseSoapChannel : EnvioTeste.nfse.WSnfseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSnfseSoapClient : System.ServiceModel.ClientBase<EnvioTeste.nfse.WSnfseSoap>, EnvioTeste.nfse.WSnfseSoap {
        
        public WSnfseSoapClient() {
        }
        
        public WSnfseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSnfseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSnfseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSnfseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Autorizar(EnvioTeste.nfse.CapaAutorizacaoNfse obj) {
            return base.Channel.Autorizar(obj);
        }
        
        public System.Threading.Tasks.Task<string> AutorizarAsync(EnvioTeste.nfse.CapaAutorizacaoNfse obj) {
            return base.Channel.AutorizarAsync(obj);
        }
        
        public string Consultar(EnvioTeste.nfse.Consultar referencia) {
            return base.Channel.Consultar(referencia);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarAsync(EnvioTeste.nfse.Consultar referencia) {
            return base.Channel.ConsultarAsync(referencia);
        }
        
        public string Consultar_testes(string referencia) {
            return base.Channel.Consultar_testes(referencia);
        }
        
        public System.Threading.Tasks.Task<string> Consultar_testesAsync(string referencia) {
            return base.Channel.Consultar_testesAsync(referencia);
        }
        
        public string Cancelar(EnvioTeste.nfse.Cancelar referencia) {
            return base.Channel.Cancelar(referencia);
        }
        
        public System.Threading.Tasks.Task<string> CancelarAsync(EnvioTeste.nfse.Cancelar referencia) {
            return base.Channel.CancelarAsync(referencia);
        }
        
        public string Cancelar_testes(string referencia) {
            return base.Channel.Cancelar_testes(referencia);
        }
        
        public System.Threading.Tasks.Task<string> Cancelar_testesAsync(string referencia) {
            return base.Channel.Cancelar_testesAsync(referencia);
        }
        
        public string GerarNfse(int id_grv, bool _isdev) {
            return base.Channel.GerarNfse(id_grv, _isdev);
        }
        
        public System.Threading.Tasks.Task<string> GerarNfseAsync(int id_grv, bool _isdev) {
            return base.Channel.GerarNfseAsync(id_grv, _isdev);
        }
    }
}
